document.querySelector("body").innerHTML = `<iframe width="560" height="315" src="https://www.youtube.com/embed/NhcefzPNoDk" title="YouTube video player"
frameborder="0"
allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
allowfullscreen></iframe>

<p>Video de coreano vlogs</p>

<p>Obelisco</p>

<iframe
src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6567.705092821983!2d-58.37703422396874!3d-34.60788997183337!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95a3352cbe276f75%3A0xe16921ef0545f86d!2sCasa%20Rosada!5e0!3m2!1ses-419!2sar!4v1680036124357!5m2!1ses-419!2sar"
width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
referrerpolicy="no-referrer-when-downgrade"></iframe>

<p>Greta Van Fleet</p>
<iframe style="border-radius:12px"
src="https://open.spotify.com/embed/track/7aOor99o8NNLZYElOXlBG1?utm_source=generator" width="100%" height="152"
frameBorder="0" allowfullscreen=""
allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

<P>MERCALIBRE</P>
<iframe height="600px" width="1200px" src="https://www.mercadolibre.com.ar" frameborder="0"></iframe>

`;